### ISSUE TITLE
Syncing local file after Twitch stream does not work

### ISSUE THREAD

**Issue by noahkw** [LenBanana/SyncStream_API#1]
The local file is not synced properly if a Twitch stream had been playing previously.
On inspecting the websocket messages, it seems that Twitch sync messages continue being exchanged.
![image](https://user-images.githubusercontent.com/6728859/163610243-f6da114b-deb0-4c41-a413-6ca7e908b315.png)

Adding a YT video, skipping it, then re-adding the local file fixes the issue.

**Comment by LenBanana** [comment]
Fixed in frontend with commit [83afab2](https://github.com/LenBanana/SyncStream_Angular/commit/83afab228fdb9dcad124c55e590a6c13369dcf9e)
